services:
  redis:
    image: redis:7-alpine
    container_name: rtmp-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - rtmp-net

  traefik:
    image: traefik:v3.7
    container_name: rtmp-traefik
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:80"
    volumes:
      - ./traefik/traefik-local.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/traefik-dynamic-dev.yml:/etc/traefik/dynamic/traefik-dynamic.yml:ro
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - rtmp-net

  rtmp-router:
    build:
      context: ../rtmp-router
      dockerfile: Dockerfile
    container_name: rtmp-router
    environment:
      REDIS_URI: "redis://redis:6379"
      RTMP_ROUTER_LISTEN: "0.0.0.0:1935"
      RTMP_ROUTER_NODE_PORT: "1935"
      RTMP_ROUTER_MAX_STREAMS_PER_NODE: "18"
      RTMP_ROUTER_ADMIN_LISTEN: "127.0.0.1:9100"
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - rtmp-net

networks:
  rtmp-net:
