http:
  routers:
    app:
      entryPoints:
        - web
      rule: PathPrefix(`/`)
      service: app
  services:
    app:
      loadBalancer:
        servers:
          - url: http://rtmp-server:8888
        strategy: p2c
        healthCheck:
          path: /health/live
          interval: 10s
          timeout: 3s
