http:
  routers:
    app:
      entryPoints:
        - web
      rule: PathPrefix(`/`)
      service: app
  services:
    app:
      loadBalancer:
        servers:
#HTTP_SERVERS
        strategy: p2c
        healthCheck:
          path: /health/ready
          interval: 10s
          timeout: 3s
tcp:
  routers:
    rtmp:
      entryPoints:
        - rtmp
      rule: HostSNI(`*`)
      service: rtmp
  services:
    rtmp:
      loadBalancer:
        servers:
#TCP_SERVERS
        healthCheck:
          interval: 15s
          timeout: 3s